---
- name: Remove temporary cloud-init files so it runs the next time
  file: path=/var/lib/cloud/ state=absent force=true

- name: Delete ssh host key files
  file: path={{ item }} state=absent
  with_fileglob:
    - /etc/ssh/ssh_host_*
